### ISSUE TITLE
StageFactory에서 PlatformResourceManager를 사용할경우 발생하는 버그

### ISSUE THREAD

**Issue by horace-velmont** [CienProject2014/OneLevelHero#113]
에러코드

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx-freetype64.dll' for target: Windows 7, 64-bit
    at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:116)
    at com.badlogic.gdx.graphics.g2d.freetype.FreeType.initFreeType(FreeType.java:541)
    at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.<init>(FreeTypeFontGenerator.java:102)
    at com.uwsoft.editor.renderer.resources.ResourceManager.loadFont(ResourceManager.java:277)
    at com.uwsoft.editor.renderer.resources.ResourceManager.loadFonts(ResourceManager.java:270)
    at com.uwsoft.editor.renderer.resources.ResourceManager.loadAssets(ResourceManager.java:184)
    at com.uwsoft.editor.renderer.resources.ResourceManager.initAllResources(ResourceManager.java:95)
    at com.mygdx.manager.PlatformResourceManager.initPlatformerResources(PlatformResourceManager.java:33)
    at com.mygdx.factory.StageFactory.makeStage(StageFactory.java:28)
    at com.mygdx.screen.MenuScreen.show(MenuScreen.java:41)
    at com.badlogic.gdx.Game.setScreen(Game.java:61)
    at com.mygdx.manager.ScreenManager.show(ScreenManager.java:38)
    at com.mygdx.controller.ScreenController.run(ScreenController.java:25)
    at com.mygdx.controller.ScreenController.<init>(ScreenController.java:15)
    at com.mygdx.game.OneLevelHero.create(OneLevelHero.java:17)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:136)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: gdx-freetype64.dll
    at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:125)
    at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:255)
    at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:114)
    ... 16 more

**Comment by horace-velmont** [comment]
에러나는 부분은 //FIXME로 주석처리해 두었음

**Comment by xzvfinet** [comment]
저거 폰트가 문제있을 때 나는 에러인데 대훈이형도 안됐어요?

**Comment by horace-velmont** [comment]
@ChoiJIN ㅇㅇ 나도 에러남 내일 한번 이유를 파악해봅시다

**Comment by horace-velmont** [comment]
http://cien.woobi.co.kr/dokuwiki/doku.php?id=%EC%A0%9C%EC%9E%91%ED%99%9C%EB%8F%99:font_%EC%85%8B%ED%8C%85
