### ISSUE TITLE
blackWood에서 마왕성 가면 꺼짐

### ISSUE THREAD

**Issue by NakOh** [CienProject2014/OneLevelHero#414]
해당 로그 

PositionManager: 현재노드 이름 - devil_castle
PositionManager: 현재위치 - node
Exception in thread "LWJGL Application" java.lang.NullPointerException
    at com.mygdx.currentState.FieldInfo.setFieldInfo(FieldInfo.java:17)
    at com.mygdx.manager.FieldManager.startMovingField(FieldManager.java:51)
    at com.mygdx.listener.ArrowButtonListener.clicked(ArrowButtonListener.java:37)
    at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
    at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
    at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:272)
    at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:94)
    at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:305)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:199)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)

**Comment by horace-velmont** [comment]
기분탓임
